# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: ArtifactoryMaven@2
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'art-test'
    targetResolveReleaseRepo: 'mvn-libs-release-local'
    targetResolveSnapshotRepo: 'mvn-libs-snapshot-local'
    artifactoryDeployService: 'art-test'
    targetDeployReleaseRepo: 'mvn-libs-release-local'
    targetDeploySnapshotRepo: 'mvn-libs-snapshot-local'
